on: [push, pull_request, workflow_dispatch]
name: Build/Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.0'
    - name: Build
      run: go build
    # - name: Test
    #   run: go test ./...
    - name: Check formatting
      run: test -z "$(go fmt ./...)"
